name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        yarn-version: [1.19.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Deploy in Github Pages
        run: |
          yarn --silent
          yarn run deploy
        env:
          CI: true
          GH_TOKEN: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
