name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@master
        with:
          node-version: 12
          yarn-version: 1.19.x
        env:
          ACCESS_TOKEN: ${{ secrets.DEPLOY_GH_PAGES_TOKEN }}
          BASE_BRANCH: master # The branch the action should deploy from.
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: example/build # The folder the action should deploy.
          BUILD_SCRIPT: yarn --silent && yarn build # The build script the action should run prior to deploying.
