name: Deploy to Github Pages

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]
        yarn-version: [1.19.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Predeploy
        run: |
          yarn --silent
        env:
          CI: true
      - name: GitHub Pages Deploy
        uses: maxheld83/ghpages@v0.2.1
        env:
          BUILD_DIR: "example/build"
        secret: ["DEPLOY_GH_PAGES_TOKEN"]
