name: Node.js Package

on:
  push:
    branches:
      - master

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://registry.npmjs.org/
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets. NPM_AUTH_TOKEN}}

  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          yarn-version: 1.19.x
          registry-url: https://npm.pkg.github.com/
          scope: "@shhdharmen"
      - run: |
        yarn --silent
        npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GH_NODE_AUTH_TOKEN}}
